In [5]:
import numpy as np

a1 = np.arange(10)  # 1D
a2 = np.arange(12).reshape(3,4) # 2D
a3 = np.arange(8).reshape(2,2,2)  # 3D

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a1[2]

np.int64(2)

In [9]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1,2]

np.int64(6)

In [14]:
a2[1,0]

np.int64(4)

In [15]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
a3[1,0,1]

np.int64(5)

In [21]:
a3[0,1,0]

np.int64(2)

In [22]:
a3[0,0,0]

np.int64(0)

In [23]:
a3[1,1,0]

np.int64(6)

**Slicing :**

In [1]:
import numpy as np

a1 = np.arange(10)  # 1D
a2 = np.arange(12).reshape(3,4) # 2D
a3 = np.arange(8).reshape(2,2,2)  # 3D

In [2]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a1[2:5]

array([2, 3, 4])

In [6]:
a1[0:8:2]

array([0, 2, 4, 6])

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a2[0,:]

array([0, 1, 2, 3])

In [9]:
a2[2,:]

array([ 8,  9, 10, 11])

In [10]:
a2[:,2]

array([ 2,  6, 10])

In [15]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [26]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [30]:
a2[::2,0:2]

array([[0, 1],
       [8, 9]])

In [32]:
a2[1:2,::3]

array([[4, 7]])

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
a3[0,1]

array([3, 4, 5])

In [44]:
a3[1,:,1]

array([10, 13, 16])

In [45]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [48]:
a3[0::2,0:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])