**Iterating :**

In [15]:
# Old way :

import numpy as np

a1 = np.arange(10)
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [19]:
# New way by using np.nditer()

for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
# Old way :
a2 = np.arange(12).reshape(3,4)
for i in a2:
    for j in i:
      print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [20]:
# New way by using np.nditer()

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [18]:
# Old way :

a3 = np.arange(27).reshape(3,3,3)

for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [22]:
# New way by using np.nditer()

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping :**

In [ ]:
# reshaping

In [24]:
# Transpose
np.transpose(a2)
a2.T  # small and easy way

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [25]:
# Ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])