**What is numpy?**

_NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more._

_At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types._

**Numpy Arrays Vs Python Sequences**

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations execute more efficiently and with less code than is possible using Python’s built-in sequences.

**Creating Numpy Arrays :**

In [1]:
# np.array
import numpy as np
from numpy import character

a = np.array([1,2,3])
print(a)   # vector

[1 2 3]


In [2]:
# 2D and 3D

b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)   # matrix

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #  3D array
print(c)    # tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# datatype array  ( dtype= )
# we are using bool and bool shows every non-zero value true !
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [8]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [11]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# with reshape
np.arange(1,11).reshape(2,5)  # there are Rows = 2 and Columns = 5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# np.random
np.random.random((3,4))

array([[0.31097422, 0.45397833, 0.31969093, 0.83659869],
       [0.6184199 , 0.49535779, 0.12143157, 0.30497364],
       [0.27689803, 0.67312675, 0.67463823, 0.13763936]])

In [24]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
# np.identity
np.identity(3, dtype=int) # np.identity(3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])