# np.sort

Return a sorted copy of an array.

In [38]:
# code :

import numpy as np

a = np.random.randint(1,100,15)
print(a)

[98 97 39 78 97 45  8 84 71 73 46 67 80 78 96]


In [46]:
b = np.random.randint(1,100, 24).reshape(6,4)
print(b)

[[19 96 14 33]
 [ 6 95 24 59]
 [23 70 86 97]
 [21 25 74 34]
 [55 87 92  8]
 [30 48 95 15]]


In [47]:
np.sort(a) # ascending order

array([ 8, 39, 45, 46, 67, 71, 73, 78, 78, 80, 84, 96, 97, 97, 98],
      dtype=int32)

In [48]:
np.sort(b) # row wise sorting # 2D

array([[14, 19, 33, 96],
       [ 6, 24, 59, 95],
       [23, 70, 86, 97],
       [21, 25, 34, 74],
       [ 8, 55, 87, 92],
       [15, 30, 48, 95]], dtype=int32)

In [49]:
np.sort(b, axis=0)

array([[ 6, 25, 14,  8],
       [19, 48, 24, 15],
       [21, 70, 74, 33],
       [23, 87, 86, 34],
       [30, 95, 92, 59],
       [55, 96, 95, 97]], dtype=int32)

In [50]:
np.sort(a)[::-1] # we can also use indexing in sorting !

array([98, 97, 97, 96, 84, 80, 78, 78, 73, 71, 67, 46, 45, 39,  8],
      dtype=int32)

# np.append()

* The numpy.append() appends values along the mentioned axis at the end of the array

In [51]:
# code :
np.append(a,200)

array([ 98,  97,  39,  78,  97,  45,   8,  84,  71,  73,  46,  67,  80,
        78,  96, 200])

In [53]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[19., 96., 14., 33.,  1.],
       [ 6., 95., 24., 59.,  1.],
       [23., 70., 86., 97.,  1.],
       [21., 25., 74., 34.,  1.],
       [55., 87., 92.,  8.,  1.],
       [30., 48., 95., 15.,  1.]])

# np.concatinate :

* numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [54]:
# code :

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [55]:
np.concatenate((c,d), axis=1) # column

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [56]:
np.concatenate((c,d), axis=0) # row

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique()

* with the help of np.unique() method, we can get the unique from an array given as parameter  in np.unique() method.

In [58]:
# code :

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])


In [59]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims()

* With the help of Numpy.extend_dims() method, we can get the expanded dimensions of an array.

In [60]:
# code :
a

array([98, 97, 39, 78, 97, 45,  8, 84, 71, 73, 46, 67, 80, 78, 96],
      dtype=int32)

In [23]:
np.expand_dims(a, axis=0).shape # rows

(1, 15)

In [22]:
np.expand_dims(a, axis=1)

array([[27],
       [90],
       [ 7],
       [15],
       [99],
       [13],
       [60],
       [31],
       [30],
       [14],
       [55],
       [79],
       [32],
       [ 8],
       [94]], dtype=int32)

# np.where() :

* The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [67]:
# code :
a

array([98, 97, 39, 78, 97, 45,  8, 84, 71, 73, 46, 67, 80, 78, 96],
      dtype=int32)

In [68]:
# find all indices with value greater than 50

np.where(a > 50)

(array([ 0,  1,  3,  4,  7,  8,  9, 11, 12, 13, 14]),)

In [69]:
# replace all values > 50 with 0
np.where(a>50,0, a) # replacing the whole greater 50 value with 0

array([ 0,  0, 39,  0,  0, 45,  8,  0,  0,  0, 46,  0,  0,  0,  0],
      dtype=int32)

In [70]:
np.where(a%2 == 0,0, a) # finding all even indexes

array([ 0, 97, 39,  0, 97, 45,  0,  0, 71, 73,  0, 67,  0,  0,  0],
      dtype=int32)

# np.argmax() :

* The Numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [71]:
# code :

a

array([98, 97, 39, 78, 97, 45,  8, 84, 71, 73, 46, 67, 80, 78, 96],
      dtype=int32)

In [74]:
np.argmax(a) # shows the biggest index number.

np.int64(0)

In [75]:
b

array([[19, 96, 14, 33],
       [ 6, 95, 24, 59],
       [23, 70, 86, 97],
       [21, 25, 74, 34],
       [55, 87, 92,  8],
       [30, 48, 95, 15]], dtype=int32)

In [78]:
np.argmax(b, axis=1)

array([1, 1, 3, 2, 2, 2])

In [79]:
np.argmax(b, axis=0)

array([4, 0, 5, 2])

# np.argmin() :


In [81]:
a

array([98, 97, 39, 78, 97, 45,  8, 84, 71, 73, 46, 67, 80, 78, 96],
      dtype=int32)

In [82]:
np.argmin(a)

np.int64(6)

# np.cumsum() :

* The numpy.cumsum() function is used when we want to computer the cumulative sum of array elements over a given axis.

In [83]:
a

array([98, 97, 39, 78, 97, 45,  8, 84, 71, 73, 46, 67, 80, 78, 96],
      dtype=int32)

In [86]:
np.cumsum(a) # this is use for calculating all elements in array index ( + )

array([  98,  195,  234,  312,  409,  454,  462,  546,  617,  690,  736,
        803,  883,  961, 1057])

In [90]:
b

array([[19, 96, 14, 33],
       [ 6, 95, 24, 59],
       [23, 70, 86, 97],
       [21, 25, 74, 34],
       [55, 87, 92,  8],
       [30, 48, 95, 15]], dtype=int32)

In [91]:
np.cumsum(b) # without axis it shows the output in 1D array

array([  19,  115,  129,  162,  168,  263,  287,  346,  369,  439,  525,
        622,  643,  668,  742,  776,  831,  918, 1010, 1018, 1048, 1096,
       1191, 1206])

In [92]:
np.cumsum(b, axis=1) # row sum

array([[ 19, 115, 129, 162],
       [  6, 101, 125, 184],
       [ 23,  93, 179, 276],
       [ 21,  46, 120, 154],
       [ 55, 142, 234, 242],
       [ 30,  78, 173, 188]])

In [93]:
np.cumsum(b, axis=0) # column sum

array([[ 19,  96,  14,  33],
       [ 25, 191,  38,  92],
       [ 48, 261, 124, 189],
       [ 69, 286, 198, 223],
       [124, 373, 290, 231],
       [154, 421, 385, 246]])

# cumprod() :


In [88]:
v = np.random.randint(1,10,6) # this is use for calculating all elements in array index ( * )

v

array([2, 8, 3, 4, 6, 9], dtype=int32)

In [89]:
np.cumprod(v)

array([    2,    16,    48,   192,  1152, 10368])

In [95]:
w = np.random.randint(1,10,6).reshape(3,2)

w

array([[9, 2],
       [7, 3],
       [6, 3]], dtype=int32)

In [96]:
np.cumprod(w , axis=1) # for row multiple

array([[ 9, 18],
       [ 7, 21],
       [ 6, 18]])

In [98]:
np.cumprod(w , axis=0) # for column multiple

array([[  9,   2],
       [ 63,   6],
       [378,  18]])