# Set Functions :
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [3]:
import numpy as np

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n) # jointing and adjusting the duplicate values

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
np.intersect1d(m,n) # Similar values in both arrays

array([3, 4, 5])

In [5]:
np.setdiff1d(m,n) # those items which are not in 'n'.

array([1, 2])

In [6]:
np.setdiff1d(n,m) # showing the values of m now which are not present.

array([6, 7])

In [7]:
np.setxor1d(m,n) # Those elements which are not similar in both arrays.

array([1, 2, 6, 7])

In [8]:
np.in1d(m,10)  # I don't know why this is not working may be it's not use in python now.

# this is basically use for searching the values through index number.

AttributeError: module 'numpy' has no attribute 'in1d'

# np.clip() :

In [10]:
a = np.random.randint(0,100,10)

a

array([80, 88, 28,  7, 21, 81, 86, 12, 65, 60], dtype=int32)

In [13]:
np.clip(a, a_min=25, a_max=75) # it is basically use for extracting the minimum and maximum

array([75, 75, 28, 25, 25, 75, 75, 25, 65, 60], dtype=int32)