# Broadcasting  :

1. **What is Broadcasting in NumPy?**

* Broadcasting is a mechanism in NumPy that allows arrays of different shapes to be used together in arithmetic operations.

* It automatically expands the smaller array to match the shape of the larger array without actually copying data.

In [3]:
# same shape
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)

print(a)
print(b)

print(a + b)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]


In [4]:
# diff shape :

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a + b)


[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [7]:
# random example :
a = np.random.randint(1,100,6).reshape(2,3)
b = np.random.randint(1,100,6).reshape(2,3)

print(a)
print(b)

print(a + b)

[[18 19 15]
 [ 2 50 75]]
[[63 54 89]
 [37 43 59]]
[[ 81  73 104]
 [ 39  93 134]]


# Broadcasting Rules :

* _Broadcasting in NumPy is a mechanism that allows operations on arrays of different shapes. It works by automatically expanding the smaller array to match the shape of the larger array, enabling element-wise computations without copying data._

**Rule 1:** _Compare dimensions from right to left_

NumPy compares the shapes of arrays starting from the last dimension (rightmost side).

**Rule 2:** _Dimensions are compatible if:_

Two dimensions are compatible when:

* They are equal
OR
* One of them is 1

**Rule 3:** _If dimensions are not compatible → Error_

If neither condition is satisfied, NumPy will raise a ValueError.

**Rule 4:** _Missing dimensions are treated as 1_

If arrays have different numbers of dimensions, the smaller one is padded with 1s on the left side.

In [ ]:
# correct way for using !

import numpy as np

a = np.arange(1).reshape(1)
b = np.arange(4).reshape(2,2)   # it is valid
print(a)
print(b)
print(a + b)


In [2]:
# this is not a correct way

import numpy as np

a = np.arange(1,4).reshape(3)
b = np.arange(12).reshape(3,4) # it is not valid because of last number 4 is greater than 3
print(a)
print(b)
print(a + b)


[1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [1]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)   # it is not valid
print(a)
print(b)
print(a + b)

NameError: name 'np' is not defined

In [3]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)   # it not is valid
print(a)
print(b)
print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

# Working with mathematical formulas

In [4]:
a = np.arange(10)
np.sum(a)


np.int64(45)

In [7]:
# sigmoid
def sigmoid(array):
    return 1/(1 + np.exp(-(array)))

a = np.arange(4)
sigmoid(a)


array([0.5       , 0.73105858, 0.88079708, 0.95257413])

In [26]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)


In [28]:
def mse(actual, predicted):
     return np.mean((actual - predicted)**2)

mse(actual, predicted)

np.float64(486.52)

In [29]:
# categorical cross entropy
np.mean((actual - predicted)**2) # short way to use the loss function

np.float64(486.52)

In [15]:

predicted

array([22, 25, 26, 13, 32,  2, 17, 24, 13,  5,  2, 25, 30, 41, 37, 10, 34,
        2, 39,  6, 19, 34, 33, 33, 31], dtype=int32)

In [16]:
actual

array([ 4, 20, 16, 27, 26, 43,  3,  2, 13, 40, 18, 49,  1, 44, 46,  2,  5,
       16, 48, 29, 42, 24, 17, 18, 21], dtype=int32)

# Working with missing values

In [ ]:
# working with missing values -> np.nan