# Broadcasting  :

1. **What is Broadcasting in NumPy?**

* Broadcasting is a mechanism in NumPy that allows arrays of different shapes to be used together in arithmetic operations.

* It automatically expands the smaller array to match the shape of the larger array without actually copying data.

In [3]:
# same shape
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)

print(a)
print(b)

print(a + b)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]


In [4]:
# diff shape :

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a + b)


[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [7]:
# random example :
a = np.random.randint(1,100,6).reshape(2,3)
b = np.random.randint(1,100,6).reshape(2,3)

print(a)
print(b)

print(a + b)

[[18 19 15]
 [ 2 50 75]]
[[63 54 89]
 [37 43 59]]
[[ 81  73 104]
 [ 39  93 134]]


# Broadcasting Rules :

* _Broadcasting in NumPy is a mechanism that allows operations on arrays of different shapes. It works by automatically expanding the smaller array to match the shape of the larger array, enabling element-wise computations without copying data._

**Rule 1:** _Compare dimensions from right to left_

NumPy compares the shapes of arrays starting from the last dimension (rightmost side).

**Rule 2:** _Dimensions are compatible if:_

Two dimensions are compatible when:

* They are equal
OR
* One of them is 1

**Rule 3:** _If dimensions are not compatible → Error_

If neither condition is satisfied, NumPy will raise a ValueError.

**Rule 4:** _Missing dimensions are treated as 1_

If arrays have different numbers of dimensions, the smaller one is padded with 1s on the left side.