**NumPy Array vs Python Lists :**

In [4]:

# speed :
# lists :
a = [ i for i in range(10000000)]
b = [i for i in range (10000000, 20000000)]

c = []

import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

2.642585039138794


In [5]:
# numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a + b

print(time.time()-start)

0.13160943984985352


In [6]:
ans = 2.64/0.13
print(ans)

20.307692307692307


In [7]:
# memory :

a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [10]:
a = np.arange(10000000, dtype=np.int8)   # int64 is default.
sys.getsizeof(a)

10000112

In [ ]:
# convenience



**Advance indexing :**

In [19]:
# Normal Indexing and Slicing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a[1,2] # indexing

np.int64(5)

In [15]:
a[1:3,1:3] # slicing

array([[4, 5],
       [7, 8]])

In [20]:
# fancy indexing
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a[[0,2,3,5]] # fancy indexing !

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [23]:
a[:,[1,2,3]]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [25]:
# boolean indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[87, 35, 79, 51],
       [40, 35, 32, 74],
       [99, 50, 27, 73],
       [54, 61, 66, 69],
       [ 2, 16, 84,  9],
       [61, 10, 98, 34]], dtype=int32)

In [29]:
# find all numbers greater than 50
a[a > 50]

array([87, 79, 51, 74, 99, 73, 54, 61, 66, 69, 84, 61, 98], dtype=int32)

In [33]:
# find out even numbers
a[a % 2 == 0]

array([40, 32, 74, 50, 54, 66,  2, 16, 84, 10, 98, 34], dtype=int32)

In [42]:
# find all numbers greater than 50 and are even
a[(a % 2 == 0) & ( a > 50 )]

array([74, 54, 66, 84, 98], dtype=int32)

In [38]:
# find all numbers not divisible by 7
a[a % 7 != 0]

array([87, 79, 51, 40, 32, 74, 99, 50, 27, 73, 54, 61, 66, 69,  2, 16,  9,
       61, 10, 34], dtype=int32)