# np.percentile() :


**percentile formula :**

P = (n/N) * 100

In [4]:
import numpy as np


a = np.random.randint(1,100, 10)
a

array([94, 97, 80, 31, 54, 29, 53,  1, 80, 87], dtype=int32)

In [6]:
np.percentile(a,50)

np.float64(67.0)

In [7]:
np.median(a)

np.float64(67.0)

# np.histogram() :

* use for frequency count.

In [9]:
a

array([94, 97, 80, 31, 54, 29, 53,  1, 80, 87], dtype=int32)

In [11]:
np.histogram(a, bins=[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100] )

(array([1, 0, 1, 1, 0, 2, 0, 0, 3, 2]),
 array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef() :

In [13]:
salary = np.array([20000, 40000, 25000, 35000, 60000 ])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin() :

In [14]:
a

array([94, 97, 80, 31, 54, 29, 53,  1, 80, 87], dtype=int32)

In [15]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False,  True, False, False, False, False, False,  True,
       False])

In [16]:
a[np.isin(a, items)]

array([80, 80], dtype=int32)

# np.flip() :

In [17]:
# code :
a

array([94, 97, 80, 31, 54, 29, 53,  1, 80, 87], dtype=int32)

In [21]:
np.flip(a) # flip or reversing the value.

array([87, 80,  1, 53, 29, 54, 31, 80, 97, 94], dtype=int32)

# np.put() :

In [22]:
# code :

a

array([94, 97, 80, 31, 54, 29, 53,  1, 80, 87], dtype=int32)

In [26]:
np.put(a, [0,1], [101, 143]) # put is for putting existing items in the array for permanently

In [27]:
a

array([101, 143,  80,  31,  54,  29,  53,   1,  80,  87], dtype=int32)

# np.delete() :

In [28]:
a

array([101, 143,  80,  31,  54,  29,  53,   1,  80,  87], dtype=int32)

In [34]:
np.delete(a,[1,2,3]) # it is use for delete the index elements and its always take the index number for deleting the array element value.

array([101,  54,  29,  53,   1,  80,  87], dtype=int32)